import json
import os
import urllib.parse

def main():
    os.makedirs("data", exist_ok=True)

    # 1. Load existing base datasets
    with open("data/squad_asean_2026.json", "r", encoding="utf-8") as f:
        squad_raw = json.load(f)
    with open("data/past_internationals_3yrs.json", "r", encoding="utf-8") as f:
        past_raw = json.load(f)
    with open("data/malaysian_prospects.json", "r", encoding="utf-8") as f:
        prospects_raw = json.load(f)

    master_players = []
    seen_names = set()
    INELIGIBLE_NAMES = {
        "mats deijl", "ferdy druijf", "manuel hidalgo", "sem scheperman",
        "julian bechler", "bérgson", "bergson", "joshua brownhill"
    }

    def is_ineligible(name_str):
        if not name_str:
            return True
        nl = name_str.lower().strip()
        return any(ine in nl for ine in INELIGIBLE_NAMES)

    # Function to generate avatar URL
    def make_avatar(name):
        enc = urllib.parse.quote(name)
        return f"https://ui-avatars.com/api/?name={enc}&background=1e293b&color=f59e0b&size=150&bold=true&font-size=0.38"

    # Add ASEAN 2026 Squad members
    for p in squad_raw:
        name = p["name"]
        if is_ineligible(name) or name in seen_names:
            continue
        seen_names.add(name)
        p["pool_status"] = "ASEAN Cup 2026 Squad"
        p["tier"] = "National Senior Squad"
        if not p.get("photo_url") or "default" in p.get("photo_url", ""):
            p["photo_url"] = make_avatar(name)
        master_players.append(p)

    # Add Past Internationals
    for p in past_raw:
        name = p["name"]
        if is_ineligible(name) or name in seen_names:
            continue
        seen_names.add(name)
        p["pool_status"] = "Senior International (2023-2026)"
        p["tier"] = "National Pool (Recent)"
        if not p.get("photo_url") or "default" in p.get("photo_url", ""):
            p["photo_url"] = make_avatar(name)
        master_players.append(p)

    # Add Prospects
    for p in prospects_raw:
        name = p["name"]
        if is_ineligible(name) or name in seen_names:
            continue
        seen_names.add(name)
        p["pool_status"] = "Heritage & Scouting Prospect"
        p["tier"] = "Prospect / Diaspora"
        if not p.get("photo_url") or "default" in p.get("photo_url", ""):
            p["photo_url"] = make_avatar(name)
        master_players.append(p)

    # Now add comprehensive domestic Malaysian players from all 13 MSL clubs
    domestic_pool = [
        # --- JOHOR DARUL TA'ZIM (JDT) ---
        {
            "id": 1001,
            "name": "Feroz Baharudin",
            "full_name": "Muhammad Feroz bin Baharudin",
            "age": 25,
            "dob": "2000-04-02",
            "height": 182,
            "position": "Centre-Back",
            "secondary_positions": ["Right-Back"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Johor Darul Ta'zim",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 5,
            "goals": 1,
            "market_value_eur": 225000,
            "minutes_25_26": 1640,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "goals_26_27": 1,
            "assists_26_27": 0,
            "fotmob_rating": 7.32,
            "sofascore_rating": 7.30,
            "attributes": {"Pace": 74, "Defending": 82, "Physical": 81, "Passing": 75, "Heading": 83, "Work Rate": 82},
            "p90_metrics": {"tackles_p90": 2.6, "interceptions_p90": 1.9, "pass_acc_pct": 89.2, "duel_win_pct": 68.4},
            "scouting_summary": "Modern ball-playing centre-back with excellent recovery anticipation and aerial security. Frequent starter for JDT in continental AFC Champions League Elite."
        },
        {
            "id": 1002,
            "name": "Syahmi Safari",
            "full_name": "Muhammad Syahmi bin Safari",
            "age": 28,
            "dob": "1998-02-05",
            "height": 170,
            "position": "Right-Back",
            "secondary_positions": ["Left-Back", "Right Midfield"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Johor Darul Ta'zim",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 28,
            "goals": 1,
            "market_value_eur": 175000,
            "minutes_25_26": 1280,
            "minutes_26_27": 320,
            "apps_26_27": 4,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.08,
            "sofascore_rating": 7.12,
            "attributes": {"Pace": 82, "Defending": 75, "Physical": 74, "Passing": 77, "Dribbling": 78, "Work Rate": 83},
            "p90_metrics": {"tackles_p90": 2.1, "interceptions_p90": 1.4, "pass_acc_pct": 84.7, "duel_win_pct": 59.1},
            "scouting_summary": "Versatile overlapping fullback noted for famous solo strike in AFF Championship. Capable of functioning seamlessly on either defensive flank."
        },
        {
            "id": 1003,
            "name": "Natxo Insa",
            "full_name": "Ignacio Insa Bohigues",
            "age": 39,
            "dob": "1986-06-09",
            "height": 180,
            "position": "Central Midfield",
            "secondary_positions": ["Defensive Midfield"],
            "position_category": "Midfielder",
            "preferred_foot": "Right",
            "club": "Johor Darul Ta'zim",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Veteran",
            "caps": 7,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1120,
            "minutes_26_27": 270,
            "apps_26_27": 3,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.40,
            "sofascore_rating": 7.45,
            "attributes": {"Pace": 64, "Defending": 80, "Physical": 73, "Passing": 88, "Vision": 87, "Work Rate": 78},
            "p90_metrics": {"key_passes_p90": 1.9, "progressive_passes_p90": 7.8, "pass_acc_pct": 91.5, "duel_win_pct": 62.0},
            "scouting_summary": "Former Celta Vigo and Levante La Liga midfielder. Masterful deep-lying tempo dictator whose positional IQ shone in Malaysia's 3-3 draw vs South Korea at Asian Cup."
        },
        {
            "id": 1004,
            "name": "Afiq Fazail",
            "full_name": "Muhammad Afiq bin Fazail",
            "age": 31,
            "dob": "1994-09-29",
            "height": 174,
            "position": "Central Midfield",
            "secondary_positions": ["Defensive Midfield"],
            "position_category": "Midfielder",
            "preferred_foot": "Right",
            "club": "Johor Darul Ta'zim",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 12,
            "goals": 0,
            "market_value_eur": 200000,
            "minutes_25_26": 1720,
            "minutes_26_27": 410,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 2,
            "fotmob_rating": 7.25,
            "sofascore_rating": 7.28,
            "attributes": {"Pace": 70, "Defending": 77, "Physical": 74, "Passing": 85, "Vision": 83, "Work Rate": 84},
            "p90_metrics": {"progressive_passes_p90": 6.8, "tackles_p90": 2.4, "pass_acc_pct": 89.8, "duel_win_pct": 60.5},
            "scouting_summary": "Elite retention and circulation midfielder with exceptional positional discipline in double-pivot systems."
        },
        {
            "id": 1005,
            "name": "Ramadhan Saifullah",
            "full_name": "Muhammad Ramadhan Saifullah bin Usman",
            "age": 25,
            "dob": "2000-12-09",
            "height": 174,
            "position": "Left Winger",
            "secondary_positions": ["Right Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Kuching City FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 4,
            "goals": 0,
            "market_value_eur": 150000,
            "minutes_25_26": 1150,
            "minutes_26_27": 490,
            "apps_26_27": 6,
            "goals_26_27": 2,
            "assists_26_27": 2,
            "fotmob_rating": 7.18,
            "sofascore_rating": 7.15,
            "attributes": {"Pace": 86, "Shooting": 75, "Passing": 72, "Dribbling": 81, "Physical": 70, "Work Rate": 79},
            "p90_metrics": {"dribbles_p90": 3.4, "key_passes_p90": 1.7, "pass_acc_pct": 79.5, "duel_win_pct": 52.8},
            "scouting_summary": "Explosive wide forward with rapid acceleration in 1v1 situations and high shot generation off inverted cuts."
        },

        # --- SELANGOR FC ---
        {
            "id": 1006,
            "name": "Azim Al Amin",
            "full_name": "Muhammad Azim Al Amin bin Kamaruddin",
            "age": 24,
            "dob": "2001-09-20",
            "height": 182,
            "position": "Goalkeeper",
            "position_category": "Goalkeeper",
            "preferred_foot": "Right",
            "club": "Selangor FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL U23 Domestic Prospect",
            "tier": "U23 National Team",
            "caps": 1,
            "goals": 0,
            "market_value_eur": 125000,
            "minutes_25_26": 900,
            "minutes_26_27": 360,
            "apps_26_27": 4,
            "clean_sheets_26_27": 2,
            "saves_p90": 3.4,
            "fotmob_rating": 7.10,
            "sofascore_rating": 7.15,
            "attributes": {"Shot Stopping": 78, "Reflexes": 81, "Handling": 75, "Positioning": 77, "Kicking": 76, "Physical": 77},
            "p90_metrics": {"save_pct": 77.5, "psxg_diff": 0.12, "pass_acc_pct": 76.2, "duel_win_pct": 60.0},
            "scouting_summary": "Agile goalkeeper with swift reaction diving and brave sweeping instincts outside the penalty area."
        },
        {
            "id": 1007,
            "name": "Sharul Nazeem",
            "full_name": "Muhammad Sharul Nazeem bin Zulpakar",
            "age": 26,
            "dob": "1999-11-16",
            "height": 180,
            "position": "Centre-Back",
            "secondary_positions": ["Right-Back"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Selangor FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 8,
            "goals": 0,
            "market_value_eur": 200000,
            "minutes_25_26": 1890,
            "minutes_26_27": 480,
            "apps_26_27": 6,
            "goals_26_27": 0,
            "assists_26_27": 0,
            "fotmob_rating": 7.22,
            "sofascore_rating": 7.25,
            "attributes": {"Pace": 76, "Defending": 81, "Physical": 82, "Passing": 74, "Heading": 82, "Work Rate": 85},
            "p90_metrics": {"tackles_p90": 2.9, "interceptions_p90": 2.2, "pass_acc_pct": 84.1, "duel_win_pct": 65.8},
            "scouting_summary": "Fierce, front-foot tackling centre-back known as 'Afro'. Excellent anticipation in breaking up counter-attacks and dominant in defensive ground duels."
        },
        {
            "id": 1008,
            "name": "Quentin Cheng",
            "full_name": "Quentin Cheng Jiun-Ho",
            "age": 26,
            "dob": "1999-11-20",
            "height": 181,
            "position": "Right-Back",
            "secondary_positions": ["Right Midfield"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Selangor FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 6,
            "goals": 0,
            "market_value_eur": 175000,
            "minutes_25_26": 1720,
            "minutes_26_27": 490,
            "apps_26_27": 6,
            "goals_26_27": 0,
            "assists_26_27": 2,
            "fotmob_rating": 7.15,
            "sofascore_rating": 7.20,
            "attributes": {"Pace": 80, "Defending": 77, "Physical": 79, "Passing": 76, "Crossing": 81, "Work Rate": 86},
            "p90_metrics": {"crosses_p90": 3.8, "tackles_p90": 2.2, "pass_acc_pct": 81.3, "duel_win_pct": 61.2},
            "scouting_summary": "Australian-born Malaysian wingback with relentless stamina, high crossing volume, and physical resilience down the right flank."
        },
        {
            "id": 1009,
            "name": "Ahmad Zikri Khalili",
            "full_name": "Ahmad Zikri bin Mohd Khalili",
            "age": 23,
            "dob": "2002-06-25",
            "height": 175,
            "position": "Left-Back",
            "secondary_positions": ["Right-Back"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Selangor FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL U23 Domestic Prospect",
            "tier": "U23 National Team",
            "caps": 2,
            "goals": 0,
            "market_value_eur": 150000,
            "minutes_25_26": 1340,
            "minutes_26_27": 360,
            "apps_26_27": 4,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.10,
            "sofascore_rating": 7.12,
            "attributes": {"Pace": 81, "Defending": 76, "Physical": 75, "Passing": 75, "Dribbling": 74, "Work Rate": 82},
            "p90_metrics": {"interceptions_p90": 1.9, "tackles_p90": 2.1, "pass_acc_pct": 83.5, "duel_win_pct": 60.1},
            "scouting_summary": "Athletic, defensively secure fullback capable of tucking inside as an inverted defender or overlapping cleanly."
        },
        {
            "id": 1010,
            "name": "V. Ruventhiran",
            "full_name": "Ruventhiran a/l Vengadesan",
            "age": 24,
            "dob": "2001-08-24",
            "height": 178,
            "position": "Left-Back",
            "secondary_positions": ["Left Winger"],
            "position_category": "Defender",
            "preferred_foot": "Left",
            "club": "Selangor FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 15,
            "goals": 0,
            "market_value_eur": 175000,
            "minutes_25_26": 1210,
            "minutes_26_27": 380,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.12,
            "sofascore_rating": 7.14,
            "attributes": {"Pace": 84, "Defending": 74, "Physical": 76, "Passing": 75, "Crossing": 78, "Work Rate": 83},
            "p90_metrics": {"dribbles_p90": 1.9, "crosses_p90": 3.1, "pass_acc_pct": 81.0, "duel_win_pct": 58.6},
            "scouting_summary": "Natural left-footed dynamic wingback with excellent recovery pace, high speed overlap, and direct crossing."
        },
        {
            "id": 1011,
            "name": "Aliff Haiqal",
            "full_name": "Muhammad Aliff Haiqal bin Lokman Hakim Lau",
            "age": 25,
            "dob": "2000-07-11",
            "height": 170,
            "position": "Attacking Midfield",
            "secondary_positions": ["Left Winger"],
            "position_category": "Midfielder",
            "preferred_foot": "Left",
            "club": "Selangor FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 2,
            "goals": 0,
            "market_value_eur": 125000,
            "minutes_25_26": 980,
            "minutes_26_27": 310,
            "apps_26_27": 5,
            "goals_26_27": 1,
            "assists_26_27": 1,
            "fotmob_rating": 7.05,
            "sofascore_rating": 7.08,
            "attributes": {"Pace": 79, "Shooting": 74, "Passing": 78, "Dribbling": 80, "Physical": 68, "Work Rate": 78},
            "p90_metrics": {"key_passes_p90": 1.6, "dribbles_p90": 2.2, "pass_acc_pct": 82.3, "duel_win_pct": 50.4},
            "scouting_summary": "Quick-footed central attacking midfielder adept at finding pockets between opposing midfield lines."
        },
        {
            "id": 1012,
            "name": "Syahir Bashah",
            "full_name": "Muhammad Syahir bin Bashah",
            "age": 24,
            "dob": "2001-09-16",
            "height": 173,
            "position": "Central Midfield",
            "secondary_positions": ["Attacking Midfield"],
            "position_category": "Midfielder",
            "preferred_foot": "Right",
            "club": "Selangor FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 3,
            "goals": 0,
            "market_value_eur": 125000,
            "minutes_25_26": 890,
            "minutes_26_27": 280,
            "apps_26_27": 4,
            "goals_26_27": 1,
            "assists_26_27": 0,
            "fotmob_rating": 7.02,
            "sofascore_rating": 7.05,
            "attributes": {"Pace": 73, "Shooting": 77, "Passing": 79, "Dribbling": 76, "Physical": 72, "Work Rate": 79},
            "p90_metrics": {"key_passes_p90": 1.4, "shots_p90": 1.8, "pass_acc_pct": 83.2, "duel_win_pct": 53.0},
            "scouting_summary": "Technical playmaker with a venomous long-range shot and accurate dead-ball delivery."
        },
        {
            "id": 1013,
            "name": "Danial Asri",
            "full_name": "Muhammad Danial Asri bin Radzi",
            "age": 25,
            "dob": "2000-04-01",
            "height": 176,
            "position": "Centre-Forward",
            "secondary_positions": ["Left Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Selangor FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 1,
            "goals": 0,
            "market_value_eur": 125000,
            "minutes_25_26": 720,
            "minutes_26_27": 240,
            "apps_26_27": 4,
            "goals_26_27": 1,
            "assists_26_27": 0,
            "fotmob_rating": 6.95,
            "sofascore_rating": 6.98,
            "attributes": {"Pace": 80, "Shooting": 76, "Passing": 70, "Dribbling": 74, "Physical": 73, "Work Rate": 80},
            "p90_metrics": {"shots_p90": 2.3, "xg_p90": 0.38, "pass_acc_pct": 77.4, "duel_win_pct": 51.5},
            "scouting_summary": "Lively presser in the forward third who runs channels diligently and finishes cleanly inside the 6-yard box."
        },

        # --- TERENGGANU FC ---
        {
            "id": 1014,
            "name": "Suhaimi Husin",
            "full_name": "Mohd Suhaimi bin Husin",
            "age": 31,
            "dob": "1994-08-09",
            "height": 182,
            "position": "Goalkeeper",
            "position_category": "Goalkeeper",
            "preferred_foot": "Right",
            "club": "Terengganu FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 3,
            "goals": 0,
            "market_value_eur": 150000,
            "minutes_25_26": 1980,
            "minutes_26_27": 540,
            "apps_26_27": 6,
            "clean_sheets_26_27": 3,
            "saves_p90": 3.7,
            "fotmob_rating": 7.20,
            "sofascore_rating": 7.24,
            "attributes": {"Shot Stopping": 82, "Reflexes": 83, "Handling": 78, "Positioning": 80, "Kicking": 74, "Physical": 76},
            "p90_metrics": {"save_pct": 80.2, "goals_prevented": 2.4, "pass_acc_pct": 74.0, "duel_win_pct": 65.0},
            "scouting_summary": "Veteran goalkeeper who earned AFC Asian Cup squad call-up. Consistent shot-stopper under heavy penalty box siege."
        },
        {
            "id": 1015,
            "name": "Rahadiazli Rahalim",
            "full_name": "Muhammad Rahadiazli bin Rahalim",
            "age": 24,
            "dob": "2001-11-01",
            "height": 192,
            "position": "Goalkeeper",
            "position_category": "Goalkeeper",
            "preferred_foot": "Right",
            "club": "Terengganu FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 2,
            "goals": 0,
            "market_value_eur": 175000,
            "minutes_25_26": 810,
            "minutes_26_27": 180,
            "apps_26_27": 2,
            "clean_sheets_26_27": 1,
            "saves_p90": 3.1,
            "fotmob_rating": 7.12,
            "sofascore_rating": 7.15,
            "attributes": {"Shot Stopping": 80, "Reflexes": 81, "Handling": 77, "Positioning": 78, "Kicking": 76, "Physical": 85},
            "p90_metrics": {"save_pct": 78.4, "high_claims_p90": 1.8, "pass_acc_pct": 73.1, "duel_win_pct": 72.0},
            "scouting_summary": "192 cm imposing shot stopper with immense aerial dominance on crossed deliveries and huge wingspan."
        },
        {
            "id": 1016,
            "name": "Safwan Mazlan",
            "full_name": "Muhammad Safwan bin Mazlan",
            "age": 24,
            "dob": "2002-01-24",
            "height": 180,
            "position": "Centre-Back",
            "secondary_positions": ["Right-Back"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Terengganu FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL U23 Domestic Prospect",
            "tier": "National Pool",
            "caps": 3,
            "goals": 0,
            "market_value_eur": 175000,
            "minutes_25_26": 1620,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.18,
            "sofascore_rating": 7.21,
            "attributes": {"Pace": 77, "Defending": 80, "Physical": 81, "Passing": 73, "Heading": 80, "Work Rate": 84},
            "p90_metrics": {"tackles_p90": 2.7, "interceptions_p90": 2.0, "pass_acc_pct": 82.4, "duel_win_pct": 64.1},
            "scouting_summary": "Composed and physically sturdy defender who progressed rapidly through Terengganu's setup into the senior national squad."
        },
        {
            "id": 1017,
            "name": "Shahrul Nizam",
            "full_name": "Muhammad Shahrul Nizam bin Ros Hasni",
            "age": 27,
            "dob": "1998-05-25",
            "height": 178,
            "position": "Centre-Back",
            "secondary_positions": ["Defensive Midfield"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Terengganu FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 4,
            "goals": 0,
            "market_value_eur": 175000,
            "minutes_25_26": 1800,
            "minutes_26_27": 540,
            "apps_26_27": 6,
            "goals_26_27": 0,
            "assists_26_27": 0,
            "fotmob_rating": 7.16,
            "sofascore_rating": 7.20,
            "attributes": {"Pace": 74, "Defending": 81, "Physical": 80, "Passing": 75, "Heading": 79, "Work Rate": 83},
            "p90_metrics": {"tackles_p90": 2.5, "interceptions_p90": 2.1, "pass_acc_pct": 85.0, "duel_win_pct": 63.8},
            "scouting_summary": "Long-time Terengganu defensive cornerstone known as 'Nijang'. Reads ground play smartly and commands the back four."
        },
        {
            "id": 1018,
            "name": "Engku Shakir",
            "full_name": "Engku Muhammad Nur Shakir bin Engku Yacob",
            "age": 27,
            "dob": "1998-10-16",
            "height": 175,
            "position": "Attacking Midfield",
            "secondary_positions": ["Right Winger", "Centre-Forward"],
            "position_category": "Midfielder",
            "preferred_foot": "Right",
            "club": "Terengganu FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 2,
            "goals": 0,
            "market_value_eur": 150000,
            "minutes_25_26": 1400,
            "minutes_26_27": 430,
            "apps_26_27": 6,
            "goals_26_27": 1,
            "assists_26_27": 2,
            "fotmob_rating": 7.08,
            "sofascore_rating": 7.12,
            "attributes": {"Pace": 78, "Shooting": 75, "Passing": 77, "Dribbling": 78, "Physical": 74, "Work Rate": 85},
            "p90_metrics": {"key_passes_p90": 1.7, "tackles_p90": 1.8, "pass_acc_pct": 80.5, "duel_win_pct": 55.4},
            "scouting_summary": "Intense pressing forward-midfielder who leads front-line counter-pressing schemes with immense tactical stamina."
        },

        # --- SABAH FC ---
        {
            "id": 1019,
            "name": "Damien Lim",
            "full_name": "Damien Lim Chien Khai",
            "age": 28,
            "dob": "1997-02-15",
            "height": 182,
            "position": "Goalkeeper",
            "position_category": "Goalkeeper",
            "preferred_foot": "Right",
            "club": "Sabah FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 1,
            "goals": 0,
            "market_value_eur": 175000,
            "minutes_25_26": 1620,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "clean_sheets_26_27": 2,
            "saves_p90": 3.5,
            "fotmob_rating": 7.14,
            "sofascore_rating": 7.18,
            "attributes": {"Shot Stopping": 81, "Reflexes": 82, "Handling": 77, "Positioning": 79, "Kicking": 76, "Physical": 78},
            "p90_metrics": {"save_pct": 79.1, "pass_acc_pct": 75.8, "duel_win_pct": 64.0},
            "scouting_summary": "Agile goalkeeper with lightning close-range reaction times and confident leadership in the penalty area."
        },
        {
            "id": 1020,
            "name": "Khairul Fahmi Che Mat",
            "full_name": "Khairul Fahmi bin Che Mat",
            "age": 37,
            "dob": "1989-01-07",
            "height": 172,
            "position": "Goalkeeper",
            "position_category": "Goalkeeper",
            "preferred_foot": "Right",
            "club": "Sabah FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Veteran",
            "caps": 85,
            "goals": 0,
            "market_value_eur": 50000,
            "minutes_25_26": 720,
            "minutes_26_27": 180,
            "apps_26_27": 2,
            "clean_sheets_26_27": 1,
            "saves_p90": 3.0,
            "fotmob_rating": 7.02,
            "sofascore_rating": 7.05,
            "attributes": {"Shot Stopping": 77, "Reflexes": 78, "Handling": 79, "Positioning": 84, "Kicking": 75, "Physical": 70},
            "p90_metrics": {"save_pct": 75.0, "pass_acc_pct": 74.2, "duel_win_pct": 58.0},
            "scouting_summary": "Legendary AFF Suzuki Cup champion goalkeeper known as 'Apek'. Exceptional reading of angles and veteran locker-room presence."
        },
        {
            "id": 1021,
            "name": "Rawilson Batuil",
            "full_name": "Rawilson Batuil",
            "age": 31,
            "dob": "1994-04-29",
            "height": 180,
            "position": "Centre-Back",
            "secondary_positions": ["Right-Back"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Sabah FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 10,
            "goals": 0,
            "market_value_eur": 125000,
            "minutes_25_26": 1250,
            "minutes_26_27": 360,
            "apps_26_27": 4,
            "goals_26_27": 0,
            "assists_26_27": 0,
            "fotmob_rating": 7.04,
            "sofascore_rating": 7.06,
            "attributes": {"Pace": 72, "Defending": 79, "Physical": 80, "Passing": 71, "Heading": 80, "Work Rate": 82},
            "p90_metrics": {"tackles_p90": 2.4, "interceptions_p90": 1.8, "pass_acc_pct": 81.2, "duel_win_pct": 62.0},
            "scouting_summary": "Physical and dedicated Sabah captain with strong man-marking execution."
        },
        {
            "id": 1022,
            "name": "Farhan Roslan",
            "full_name": "Muhammad Farhan bin Roslan",
            "age": 29,
            "dob": "1996-12-03",
            "height": 160,
            "position": "Left Winger",
            "secondary_positions": ["Right Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Sabah FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 8,
            "goals": 1,
            "market_value_eur": 150000,
            "minutes_25_26": 1390,
            "minutes_26_27": 420,
            "apps_26_27": 6,
            "goals_26_27": 1,
            "assists_26_27": 2,
            "fotmob_rating": 7.10,
            "sofascore_rating": 7.12,
            "attributes": {"Pace": 85, "Shooting": 72, "Passing": 75, "Dribbling": 83, "Physical": 62, "Work Rate": 81},
            "p90_metrics": {"dribbles_p90": 3.6, "key_passes_p90": 1.8, "pass_acc_pct": 79.8, "duel_win_pct": 49.5},
            "scouting_summary": "Known as 'Messi Kedah'. Low center of gravity gives him blistering change-of-direction dribbling and fouls won in the final third."
        },
        {
            "id": 1023,
            "name": "Jafri Chew",
            "full_name": "Muhammad Jafri bin Firdaus Chew",
            "age": 28,
            "dob": "1997-06-11",
            "height": 178,
            "position": "Centre-Forward",
            "secondary_positions": ["Right Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Sabah FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 3,
            "goals": 0,
            "market_value_eur": 125000,
            "minutes_25_26": 1050,
            "minutes_26_27": 340,
            "apps_26_27": 5,
            "goals_26_27": 2,
            "assists_26_27": 1,
            "fotmob_rating": 7.02,
            "sofascore_rating": 7.05,
            "attributes": {"Pace": 78, "Shooting": 75, "Passing": 71, "Dribbling": 74, "Physical": 79, "Work Rate": 82},
            "p90_metrics": {"shots_p90": 2.1, "aerial_duels_won_p90": 2.8, "pass_acc_pct": 76.5, "duel_win_pct": 54.0},
            "scouting_summary": "Rugged target forward with strong hold-up play against physical centre-backs and relentless pressing."
        },

        # --- KUALA LUMPUR CITY FC ---
        {
            "id": 1024,
            "name": "Declan Lambert",
            "full_name": "Declan Joshua Lambert",
            "age": 27,
            "dob": "1998-09-21",
            "height": 182,
            "position": "Right-Back",
            "secondary_positions": ["Left-Back", "Centre-Back"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Kuala Lumpur City FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 4,
            "goals": 0,
            "market_value_eur": 225000,
            "minutes_25_26": 1750,
            "minutes_26_27": 540,
            "apps_26_27": 6,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.20,
            "sofascore_rating": 7.22,
            "attributes": {"Pace": 79, "Defending": 80, "Physical": 82, "Passing": 76, "Heading": 80, "Work Rate": 85},
            "p90_metrics": {"tackles_p90": 2.8, "interceptions_p90": 2.0, "pass_acc_pct": 83.2, "duel_win_pct": 65.4},
            "scouting_summary": "Australian-born Malaysian international fullback. Physically robust in 1v1 defensive isolation and versatile across back-four positions."
        },
        {
            "id": 1025,
            "name": "Ryan Lambert",
            "full_name": "Ryan Sean Lambert",
            "age": 27,
            "dob": "1998-09-21",
            "height": 180,
            "position": "Central Midfield",
            "secondary_positions": ["Defensive Midfield"],
            "position_category": "Midfielder",
            "preferred_foot": "Right",
            "club": "Kuala Lumpur City FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 3,
            "goals": 0,
            "market_value_eur": 200000,
            "minutes_25_26": 1680,
            "minutes_26_27": 490,
            "apps_26_27": 6,
            "goals_26_27": 1,
            "assists_26_27": 2,
            "fotmob_rating": 7.18,
            "sofascore_rating": 7.21,
            "attributes": {"Pace": 74, "Defending": 78, "Physical": 79, "Passing": 82, "Vision": 80, "Work Rate": 83},
            "p90_metrics": {"progressive_passes_p90": 5.9, "tackles_p90": 2.3, "pass_acc_pct": 86.4, "duel_win_pct": 61.0},
            "scouting_summary": "Twin brother of Declan. Balanced box-to-box midfielder with Dutch and Australian academy training, adept at line-breaking passes."
        },
        {
            "id": 1026,
            "name": "Kenny Pallraj",
            "full_name": "Kenny Pallraj a/l Davaragi",
            "age": 32,
            "dob": "1993-04-21",
            "height": 178,
            "position": "Defensive Midfield",
            "secondary_positions": ["Central Midfield"],
            "position_category": "Midfielder",
            "preferred_foot": "Right",
            "club": "Kuala Lumpur City FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Veteran",
            "caps": 10,
            "goals": 0,
            "market_value_eur": 125000,
            "minutes_25_26": 1350,
            "minutes_26_27": 360,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 0,
            "fotmob_rating": 7.05,
            "sofascore_rating": 7.08,
            "attributes": {"Pace": 70, "Defending": 80, "Physical": 82, "Passing": 75, "Tackling": 83, "Work Rate": 85},
            "p90_metrics": {"tackles_p90": 3.1, "interceptions_p90": 2.1, "pass_acc_pct": 82.5, "duel_win_pct": 63.5},
            "scouting_summary": "Aggressive, combative holding midfielder specializing in defensive second-ball recoveries and disrupting opposing counters."
        },
        {
            "id": 1027,
            "name": "Sean Selvaraj",
            "full_name": "Sean Eugene Selvaraj",
            "age": 29,
            "dob": "1996-04-11",
            "height": 176,
            "position": "Right Winger",
            "secondary_positions": ["Left Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Kuala Lumpur City FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 2,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 920,
            "minutes_26_27": 280,
            "apps_26_27": 4,
            "goals_26_27": 1,
            "assists_26_27": 1,
            "fotmob_rating": 6.98,
            "sofascore_rating": 7.02,
            "attributes": {"Pace": 82, "Shooting": 73, "Passing": 72, "Dribbling": 77, "Physical": 71, "Work Rate": 78},
            "p90_metrics": {"dribbles_p90": 2.4, "crosses_p90": 2.3, "pass_acc_pct": 78.4, "duel_win_pct": 48.0},
            "scouting_summary": "Direct, speedy wide attacker capable of explosive counter-attacking runs into open channels."
        },

        # --- KUCHING CITY FC ---
        {
            "id": 1028,
            "name": "Rodney Celvin",
            "full_name": "Rodney Celvin Akwensivie",
            "age": 29,
            "dob": "1996-11-25",
            "height": 185,
            "position": "Centre-Back",
            "secondary_positions": ["Right-Back"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Kuching City FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 4,
            "goals": 0,
            "market_value_eur": 175000,
            "minutes_25_26": 1710,
            "minutes_26_27": 540,
            "apps_26_27": 6,
            "goals_26_27": 1,
            "assists_26_27": 0,
            "fotmob_rating": 7.24,
            "sofascore_rating": 7.28,
            "attributes": {"Pace": 75, "Defending": 82, "Physical": 86, "Passing": 73, "Heading": 85, "Work Rate": 83},
            "p90_metrics": {"aerial_duels_won_pct": 72.5, "tackles_p90": 2.6, "pass_acc_pct": 83.0, "duel_win_pct": 69.2},
            "scouting_summary": "Ghanaian-Malaysian towering centre-back with dominant aerial reach, strength in shoulder-to-shoulder challenges, and set-piece threat."
        },
        {
            "id": 1029,
            "name": "Jimmy Raymond",
            "full_name": "Jimmy Raymond",
            "age": 28,
            "dob": "1997-04-12",
            "height": 175,
            "position": "Right-Back",
            "secondary_positions": ["Right Midfield"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Kuching City FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 125000,
            "minutes_25_26": 1420,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.05,
            "sofascore_rating": 7.08,
            "attributes": {"Pace": 78, "Defending": 76, "Physical": 77, "Passing": 73, "Work Rate": 84, "Tackling": 77},
            "p90_metrics": {"tackles_p90": 2.5, "interceptions_p90": 1.7, "pass_acc_pct": 81.0, "duel_win_pct": 58.2},
            "scouting_summary": "Tenacious Sarawakian fullback who offers reliable defensive containment and steady running along the right flank."
        },
        {
            "id": 1030,
            "name": "Nur Shamie Iszuan",
            "full_name": "Nur Shamie Iszuan bin Amin",
            "age": 30,
            "dob": "1995-09-10",
            "height": 170,
            "position": "Right Winger",
            "secondary_positions": ["Left Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Kuching City FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 6,
            "goals": 1,
            "market_value_eur": 125000,
            "minutes_25_26": 1380,
            "minutes_26_27": 410,
            "apps_26_27": 5,
            "goals_26_27": 1,
            "assists_26_27": 2,
            "fotmob_rating": 7.10,
            "sofascore_rating": 7.12,
            "attributes": {"Pace": 81, "Shooting": 73, "Passing": 76, "Dribbling": 79, "Physical": 68, "Work Rate": 80},
            "p90_metrics": {"key_passes_p90": 1.9, "crosses_p90": 2.8, "pass_acc_pct": 79.2, "duel_win_pct": 51.5},
            "scouting_summary": "Tricky wide player who previously featured in AFF Suzuki Cup. Excellent crosser and sharp in tight spaces."
        },

        # --- PERAK FC ---
        {
            "id": 1031,
            "name": "Tommy Mawat Bada",
            "full_name": "Tommy Mawat anak Bada",
            "age": 30,
            "dob": "1995-06-26",
            "height": 174,
            "position": "Left-Back",
            "secondary_positions": ["Left Midfield"],
            "position_category": "Defender",
            "preferred_foot": "Left",
            "club": "Perak FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 2,
            "goals": 0,
            "market_value_eur": 125000,
            "minutes_25_26": 1540,
            "minutes_26_27": 470,
            "apps_26_27": 6,
            "goals_26_27": 0,
            "assists_26_27": 2,
            "fotmob_rating": 7.08,
            "sofascore_rating": 7.11,
            "attributes": {"Pace": 80, "Defending": 76, "Physical": 79, "Passing": 74, "Crossing": 78, "Work Rate": 85},
            "p90_metrics": {"tackles_p90": 2.7, "crosses_p90": 3.4, "pass_acc_pct": 80.2, "duel_win_pct": 60.0},
            "scouting_summary": "High-octane left wingback with aggressive physical dueling and dangerous delivery on deep crosses."
        },
        {
            "id": 1032,
            "name": "Wan Zack Haikal",
            "full_name": "Wan Zack Haikal bin Wan Noor",
            "age": 34,
            "dob": "1991-01-28",
            "height": 170,
            "position": "Attacking Midfield",
            "secondary_positions": ["Right Winger", "Left Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Perak FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Veteran",
            "caps": 32,
            "goals": 4,
            "market_value_eur": 100000,
            "minutes_25_26": 1450,
            "minutes_26_27": 430,
            "apps_26_27": 6,
            "goals_26_27": 1,
            "assists_26_27": 3,
            "fotmob_rating": 7.22,
            "sofascore_rating": 7.25,
            "attributes": {"Pace": 74, "Shooting": 78, "Passing": 82, "Dribbling": 81, "Vision": 84, "Work Rate": 76},
            "p90_metrics": {"key_passes_p90": 2.4, "progressive_passes_p90": 5.8, "pass_acc_pct": 83.7, "duel_win_pct": 52.0},
            "scouting_summary": "Former FC Ryukyu (Japan) attacker and national team legend. Outstanding dead-ball specialist and creative hub for Perak."
        },
        {
            "id": 1033,
            "name": "Ariff Ar-Rasyid",
            "full_name": "Muhammad Ariff Ar-Rasyid bin Ariffin",
            "age": 25,
            "dob": "2000-08-14",
            "height": 178,
            "position": "Centre-Back",
            "secondary_positions": ["Right-Back"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Perak FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1380,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 0,
            "fotmob_rating": 7.02,
            "sofascore_rating": 7.06,
            "attributes": {"Pace": 75, "Defending": 77, "Physical": 78, "Passing": 72, "Heading": 78, "Work Rate": 82},
            "p90_metrics": {"interceptions_p90": 1.9, "tackles_p90": 2.3, "pass_acc_pct": 82.0, "duel_win_pct": 61.5},
            "scouting_summary": "Reliable Perak defensive stalwart who marshals the central defensive line effectively."
        },
        {
            "id": 1034,
            "name": "Firdaus Saiyadi",
            "full_name": "Ahmad Firdaus bin Saiyadi",
            "age": 28,
            "dob": "1996-10-22",
            "height": 172,
            "position": "Attacking Midfield",
            "secondary_positions": ["Central Midfield"],
            "position_category": "Midfielder",
            "preferred_foot": "Right",
            "club": "Perak FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 1,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1100,
            "minutes_26_27": 320,
            "apps_26_27": 4,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.00,
            "sofascore_rating": 7.04,
            "attributes": {"Pace": 74, "Shooting": 73, "Passing": 77, "Dribbling": 78, "Physical": 71, "Work Rate": 80},
            "p90_metrics": {"key_passes_p90": 1.5, "dribbles_p90": 2.1, "pass_acc_pct": 81.5, "duel_win_pct": 51.0},
            "scouting_summary": "Nimble attacking midfielder capable of quick wall-passes and penetrating half-spaces."
        },

        # --- KEDAH DARUL AMAN FC ---
        {
            "id": 1035,
            "name": "Kalamullah Al-Hafiz",
            "full_name": "Kalamullah Al-Hafiz bin Mat Rowi",
            "age": 30,
            "dob": "1995-07-30",
            "height": 186,
            "position": "Goalkeeper",
            "position_category": "Goalkeeper",
            "preferred_foot": "Right",
            "club": "Kedah Darul Aman FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 3,
            "goals": 0,
            "market_value_eur": 200000,
            "minutes_25_26": 1980,
            "minutes_26_27": 540,
            "apps_26_27": 6,
            "clean_sheets_26_27": 3,
            "saves_p90": 3.6,
            "fotmob_rating": 7.25,
            "sofascore_rating": 7.28,
            "attributes": {"Shot Stopping": 83, "Reflexes": 84, "Handling": 80, "Positioning": 81, "Kicking": 77, "Physical": 80},
            "p90_metrics": {"save_pct": 81.0, "pass_acc_pct": 77.2, "duel_win_pct": 68.0},
            "scouting_summary": "Starting Kedah goalkeeper and longtime Malaysia squad call-up. Very strong command of his box and consistent reflex stops."
        },
        {
            "id": 1036,
            "name": "Ariff Farhan Isa",
            "full_name": "Muhammad Ariff Farhan bin Muhammad Isa",
            "age": 29,
            "dob": "1996-07-14",
            "height": 172,
            "position": "Right-Back",
            "secondary_positions": ["Defensive Midfield", "Central Midfield"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Kedah Darul Aman FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 5,
            "goals": 0,
            "market_value_eur": 150000,
            "minutes_25_26": 1650,
            "minutes_26_27": 490,
            "apps_26_27": 6,
            "goals_26_27": 0,
            "assists_26_27": 2,
            "fotmob_rating": 7.15,
            "sofascore_rating": 7.18,
            "attributes": {"Pace": 78, "Defending": 78, "Physical": 76, "Passing": 79, "Work Rate": 85, "Tactical IQ": 83},
            "p90_metrics": {"tackles_p90": 2.5, "pass_acc_pct": 85.2, "duel_win_pct": 62.0},
            "scouting_summary": "Highly intelligent utility player comfortable both as an inverted fullback and as a midfield controller."
        },
        {
            "id": 1037,
            "name": "Fayadh Zulkifli",
            "full_name": "Mohamad Fayadh bin Mohd Zulkifli Amin",
            "age": 27,
            "dob": "1998-09-13",
            "height": 168,
            "position": "Left Winger",
            "secondary_positions": ["Right Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Kedah Darul Aman FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 4,
            "goals": 0,
            "market_value_eur": 150000,
            "minutes_25_26": 1280,
            "minutes_26_27": 390,
            "apps_26_27": 5,
            "goals_26_27": 2,
            "assists_26_27": 1,
            "fotmob_rating": 7.12,
            "sofascore_rating": 7.15,
            "attributes": {"Pace": 88, "Shooting": 75, "Passing": 73, "Dribbling": 82, "Physical": 67, "Work Rate": 80},
            "p90_metrics": {"dribbles_p90": 3.8, "shots_p90": 2.2, "pass_acc_pct": 78.5, "duel_win_pct": 52.4},
            "scouting_summary": "One of the quickest wingers in Malaysian football. Super-sub threat whose sheer pace stretches tired backlines late in games."
        },
        {
            "id": 1038,
            "name": "Syafiq Ahmad",
            "full_name": "Muhammad Syafiq bin Ahmad",
            "age": 30,
            "dob": "1995-06-28",
            "height": 178,
            "position": "Centre-Forward",
            "secondary_positions": ["Attacking Midfield", "Second Striker"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Kedah Darul Aman FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 38,
            "goals": 10,
            "market_value_eur": 225000,
            "minutes_25_26": 1550,
            "minutes_26_27": 490,
            "apps_26_27": 6,
            "goals_26_27": 4,
            "assists_26_27": 2,
            "fotmob_rating": 7.35,
            "sofascore_rating": 7.38,
            "attributes": {"Pace": 79, "Shooting": 83, "Passing": 78, "Dribbling": 78, "Heading": 84, "Physical": 79},
            "p90_metrics": {"goals_p90": 0.73, "shots_p90": 3.1, "pass_acc_pct": 81.4, "duel_win_pct": 58.7},
            "scouting_summary": "Prolific national team striker with 10 international goals. Exceptional aerial leap, instinctive penalty-box positioning, and clinical one-touch finishing."
        },
        {
            "id": 1039,
            "name": "Rizal Ghazali",
            "full_name": "Mohd Rizal bin Mohd Ghazali",
            "age": 33,
            "dob": "1992-10-01",
            "height": 175,
            "position": "Right-Back",
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Kedah Darul Aman FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Veteran",
            "caps": 21,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1320,
            "minutes_26_27": 360,
            "apps_26_27": 4,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.02,
            "sofascore_rating": 7.05,
            "attributes": {"Pace": 75, "Defending": 78, "Physical": 78, "Passing": 74, "Work Rate": 83, "Tackling": 80},
            "p90_metrics": {"tackles_p90": 2.6, "interceptions_p90": 1.7, "pass_acc_pct": 81.0, "duel_win_pct": 60.5},
            "scouting_summary": "Experienced former Harimau Malaya starting right-back with strong defensive recovery and veteran positioning."
        },

        # --- SRI PAHANG FC ---
        {
            "id": 1040,
            "name": "Zarif Irfan",
            "full_name": "Muhammad Zarif Irfan bin Hashimuddin",
            "age": 30,
            "dob": "1995-02-21",
            "height": 184,
            "position": "Goalkeeper",
            "position_category": "Goalkeeper",
            "preferred_foot": "Right",
            "club": "Sri Pahang FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 125000,
            "minutes_25_26": 1530,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "clean_sheets_26_27": 2,
            "saves_p90": 3.3,
            "fotmob_rating": 7.08,
            "sofascore_rating": 7.12,
            "attributes": {"Shot Stopping": 79, "Reflexes": 80, "Handling": 77, "Positioning": 78, "Kicking": 74, "Physical": 78},
            "p90_metrics": {"save_pct": 77.2, "pass_acc_pct": 74.5, "duel_win_pct": 63.0},
            "scouting_summary": "Dependable starting keeper for Sri Pahang with calm penalty box authority."
        },
        {
            "id": 1041,
            "name": "Fadhli Shas",
            "full_name": "Mohd Fadhli bin Mohd Shas",
            "age": 34,
            "dob": "1991-01-21",
            "height": 184,
            "position": "Centre-Back",
            "position_category": "Defender",
            "preferred_foot": "Left",
            "club": "Sri Pahang FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Veteran",
            "caps": 54,
            "goals": 1,
            "market_value_eur": 100000,
            "minutes_25_26": 1620,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 0,
            "fotmob_rating": 7.10,
            "sofascore_rating": 7.15,
            "attributes": {"Pace": 68, "Defending": 81, "Physical": 82, "Passing": 75, "Heading": 83, "Work Rate": 78},
            "p90_metrics": {"interceptions_p90": 2.2, "tackles_p90": 2.1, "pass_acc_pct": 84.8, "duel_win_pct": 66.0},
            "scouting_summary": "54-cap Malaysian international centre-back and 2010 Suzuki Cup champion. Left-footed build-up passer with vast experience."
        },
        {
            "id": 1042,
            "name": "Azrif Nasrulhaq",
            "full_name": "Muhammad Azrif Nasrulhaq bin Badrul Hisham",
            "age": 33,
            "dob": "1991-05-27",
            "height": 174,
            "position": "Right-Back",
            "secondary_positions": ["Left-Back", "Right Midfield"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Sri Pahang FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Veteran",
            "caps": 14,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1440,
            "minutes_26_27": 380,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.05,
            "sofascore_rating": 7.08,
            "attributes": {"Pace": 76, "Defending": 77, "Physical": 75, "Passing": 75, "Crossing": 77, "Work Rate": 82},
            "p90_metrics": {"tackles_p90": 2.3, "crosses_p90": 2.7, "pass_acc_pct": 81.4, "duel_win_pct": 59.0},
            "scouting_summary": "Experienced fullback with previous silverware at Selangor and JDT. Strong technical crossing."
        },
        {
            "id": 1043,
            "name": "Syazwan Andik",
            "full_name": "Muhammad Syazwan Andik bin Mohd Ishak",
            "age": 29,
            "dob": "1996-08-04",
            "height": 174,
            "position": "Left-Back",
            "position_category": "Defender",
            "preferred_foot": "Left",
            "club": "Sri Pahang FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 19,
            "goals": 1,
            "market_value_eur": 125000,
            "minutes_25_26": 1390,
            "minutes_26_27": 360,
            "apps_26_27": 4,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.04,
            "sofascore_rating": 7.06,
            "attributes": {"Pace": 79, "Defending": 75, "Physical": 74, "Passing": 76, "Crossing": 79, "Work Rate": 81},
            "p90_metrics": {"crosses_p90": 3.0, "interceptions_p90": 1.6, "pass_acc_pct": 80.8, "duel_win_pct": 57.0},
            "scouting_summary": "19-cap senior international left-back who reached 2018 AFF final. Natural left-footed delivery and reliable overlapping width."
        },
        {
            "id": 1044,
            "name": "David Rowley",
            "full_name": "David William Rowley",
            "age": 35,
            "dob": "1990-02-06",
            "height": 186,
            "position": "Central Midfield",
            "secondary_positions": ["Attacking Midfield", "Centre-Forward"],
            "position_category": "Midfielder",
            "preferred_foot": "Right",
            "club": "Sri Pahang FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 6,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1290,
            "minutes_26_27": 310,
            "apps_26_27": 4,
            "goals_26_27": 1,
            "assists_26_27": 0,
            "fotmob_rating": 7.02,
            "sofascore_rating": 7.06,
            "attributes": {"Pace": 68, "Defending": 75, "Physical": 83, "Passing": 77, "Heading": 84, "Work Rate": 80},
            "p90_metrics": {"aerial_duels_won_p90": 3.4, "tackles_p90": 2.1, "pass_acc_pct": 80.5, "duel_win_pct": 64.5},
            "scouting_summary": "Australian-born Malaysian midfielder with imposing physical frame. Excellent set-piece aerial target and physical ball-winner."
        },

        # --- PENANG FC ---
        {
            "id": 1045,
            "name": "Sikh Izhan Nazrel",
            "full_name": "Sikh Izhan Nazrel bin Sikh Azman",
            "age": 24,
            "dob": "2002-03-23",
            "height": 184,
            "position": "Goalkeeper",
            "position_category": "Goalkeeper",
            "preferred_foot": "Right",
            "club": "Penang FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL U23 Domestic Prospect",
            "tier": "National Pool",
            "caps": 2,
            "goals": 0,
            "market_value_eur": 175000,
            "minutes_25_26": 1800,
            "minutes_26_27": 540,
            "apps_26_27": 6,
            "clean_sheets_26_27": 2,
            "saves_p90": 3.8,
            "fotmob_rating": 7.22,
            "sofascore_rating": 7.26,
            "attributes": {"Shot Stopping": 82, "Reflexes": 84, "Handling": 79, "Positioning": 80, "Kicking": 82, "Physical": 79},
            "p90_metrics": {"save_pct": 80.5, "pass_acc_pct": 79.5, "long_pass_acc_pct": 58.2, "duel_win_pct": 65.0},
            "scouting_summary": "One of the most promising young goalkeepers in Malaysia. Elite footwork and passing distribution from the back with fearless sweeping."
        },
        {
            "id": 1046,
            "name": "Fairuz Zakaria",
            "full_name": "Muhammad Fairuz bin Abdul Zakaria",
            "age": 28,
            "dob": "1997-05-24",
            "height": 178,
            "position": "Right-Back",
            "secondary_positions": ["Centre-Back"],
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Penang FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1450,
            "minutes_26_27": 410,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.01,
            "sofascore_rating": 7.04,
            "attributes": {"Pace": 76, "Defending": 76, "Physical": 78, "Passing": 72, "Tackling": 78, "Work Rate": 83},
            "p90_metrics": {"tackles_p90": 2.5, "interceptions_p90": 1.7, "pass_acc_pct": 80.2, "duel_win_pct": 59.4},
            "scouting_summary": "Hard-tackling fullback who anchors the right side of Penang's defensive unit."
        },
        {
            "id": 1047,
            "name": "Nik Akif Syahiran",
            "full_name": "Nik Akif Syahiran bin Nik Mat",
            "age": 26,
            "dob": "1999-05-11",
            "height": 172,
            "position": "Central Midfield",
            "secondary_positions": ["Attacking Midfield"],
            "position_category": "Midfielder",
            "preferred_foot": "Right",
            "club": "Penang FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 6,
            "goals": 0,
            "market_value_eur": 150000,
            "minutes_25_26": 1580,
            "minutes_26_27": 470,
            "apps_26_27": 6,
            "goals_26_27": 1,
            "assists_26_27": 2,
            "fotmob_rating": 7.16,
            "sofascore_rating": 7.20,
            "attributes": {"Pace": 74, "Defending": 73, "Physical": 72, "Passing": 83, "Vision": 84, "Work Rate": 81},
            "p90_metrics": {"key_passes_p90": 2.1, "progressive_passes_p90": 5.4, "pass_acc_pct": 84.5, "duel_win_pct": 54.0},
            "scouting_summary": "Former Malaysia U23 playmaker with velvet touch, exquisite set-piece curving deliveries, and progressive vertical passes."
        },
        {
            "id": 1048,
            "name": "Amer Azahar",
            "full_name": "Muhammad Amer bin Azahar",
            "age": 29,
            "dob": "1995-06-22",
            "height": 174,
            "position": "Right Winger",
            "secondary_positions": ["Left Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Penang FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1200,
            "minutes_26_27": 360,
            "apps_26_27": 4,
            "goals_26_27": 1,
            "assists_26_27": 1,
            "fotmob_rating": 6.96,
            "sofascore_rating": 7.00,
            "attributes": {"Pace": 81, "Shooting": 72, "Passing": 73, "Dribbling": 76, "Physical": 70, "Work Rate": 79},
            "p90_metrics": {"dribbles_p90": 2.2, "crosses_p90": 2.5, "pass_acc_pct": 77.8, "duel_win_pct": 49.0},
            "scouting_summary": "Direct runner down the touchline who creates crossing opportunities with sudden bursts."
        },

        # --- PDRM FC ---
        {
            "id": 1049,
            "name": "Bryan See",
            "full_name": "Bryan See Tian Keat",
            "age": 32,
            "dob": "1993-06-22",
            "height": 188,
            "position": "Goalkeeper",
            "position_category": "Goalkeeper",
            "preferred_foot": "Right",
            "club": "PDRM FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 125000,
            "minutes_25_26": 1710,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "clean_sheets_26_27": 2,
            "saves_p90": 3.7,
            "fotmob_rating": 7.15,
            "sofascore_rating": 7.18,
            "attributes": {"Shot Stopping": 81, "Reflexes": 82, "Handling": 78, "Positioning": 80, "Kicking": 76, "Physical": 81},
            "p90_metrics": {"save_pct": 79.4, "pass_acc_pct": 75.0, "duel_win_pct": 66.0},
            "scouting_summary": "188 cm goalkeeper with US NCAA college experience (UC Irvine). Confident communicator with high aerial reach."
        },
        {
            "id": 1050,
            "name": "Norfiqrie Talib",
            "full_name": "Muhammad Norfiqrie bin Abdul Talib",
            "age": 29,
            "dob": "1996-01-31",
            "height": 175,
            "position": "Left-Back",
            "position_category": "Defender",
            "preferred_foot": "Left",
            "club": "PDRM FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1520,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 0,
            "fotmob_rating": 7.02,
            "sofascore_rating": 7.05,
            "attributes": {"Pace": 76, "Defending": 77, "Physical": 77, "Passing": 72, "Tackling": 79, "Work Rate": 83},
            "p90_metrics": {"tackles_p90": 2.8, "interceptions_p90": 1.9, "pass_acc_pct": 79.8, "duel_win_pct": 60.5},
            "scouting_summary": "Defensive-first left-back who provides stability in low-block defensive structures."
        },
        {
            "id": 1051,
            "name": "Shahrel Fikri",
            "full_name": "Muhammad Shahrel Fikri bin Md Fauzi",
            "age": 31,
            "dob": "1994-10-17",
            "height": 180,
            "position": "Centre-Forward",
            "secondary_positions": ["Right Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "PDRM FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 18,
            "goals": 5,
            "market_value_eur": 150000,
            "minutes_25_26": 1390,
            "minutes_26_27": 410,
            "apps_26_27": 5,
            "goals_26_27": 2,
            "assists_26_27": 1,
            "fotmob_rating": 7.12,
            "sofascore_rating": 7.15,
            "attributes": {"Pace": 78, "Shooting": 80, "Passing": 74, "Dribbling": 76, "Heading": 79, "Physical": 77},
            "p90_metrics": {"goals_p90": 0.44, "shots_p90": 2.5, "pass_acc_pct": 78.0, "duel_win_pct": 53.0},
            "scouting_summary": "Known as 'Eki'. Former MSL Best Striker and Nakhon Ratchasima (Thai League) player. Intelligent runs behind backlines."
        },

        # --- NEGERI SEMBILAN FC ---
        {
            "id": 1052,
            "name": "R. Kogileswaran",
            "full_name": "Kogileswaran Raj a/l Mohana Raj",
            "age": 26,
            "dob": "1998-09-21",
            "height": 172,
            "position": "Attacking Midfield",
            "secondary_positions": ["Left Winger", "Second Striker"],
            "position_category": "Midfielder",
            "preferred_foot": "Right",
            "club": "Negeri Sembilan FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 8,
            "goals": 2,
            "market_value_eur": 150000,
            "minutes_25_26": 1280,
            "minutes_26_27": 430,
            "apps_26_27": 5,
            "goals_26_27": 2,
            "assists_26_27": 2,
            "fotmob_rating": 7.18,
            "sofascore_rating": 7.22,
            "attributes": {"Pace": 79, "Shooting": 78, "Passing": 80, "Dribbling": 81, "Free Kicks": 85, "Work Rate": 78},
            "p90_metrics": {"key_passes_p90": 2.0, "shots_p90": 2.3, "pass_acc_pct": 82.5, "duel_win_pct": 52.0},
            "scouting_summary": "Former K-League 2 midfielder with Chungbuk Cheongju. Lethal free-kick converter with sublime curling technique and vision."
        },
        {
            "id": 1053,
            "name": "Barathkumar Ramaloo",
            "full_name": "Barathkumar a/l Ramaloo",
            "age": 32,
            "dob": "1992-04-23",
            "height": 176,
            "position": "Central Midfield",
            "secondary_positions": ["Defensive Midfield"],
            "position_category": "Midfielder",
            "preferred_foot": "Right",
            "club": "Negeri Sembilan FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1450,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 1,
            "fotmob_rating": 7.02,
            "sofascore_rating": 7.05,
            "attributes": {"Pace": 72, "Defending": 77, "Physical": 79, "Passing": 76, "Work Rate": 85, "Tackling": 78},
            "p90_metrics": {"tackles_p90": 2.7, "interceptions_p90": 1.8, "pass_acc_pct": 81.5, "duel_win_pct": 59.8},
            "scouting_summary": "High-stamina central midfielder who covers immense ground in midfield transitions and tackles aggressively."
        },
        {
            "id": 1054,
            "name": "N. Thanabalan",
            "full_name": "Thanabalan a/l Nadarajah",
            "age": 30,
            "dob": "1995-02-25",
            "height": 175,
            "position": "Right Winger",
            "secondary_positions": ["Centre-Forward"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Negeri Sembilan FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Veteran",
            "caps": 3,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1100,
            "minutes_26_27": 280,
            "apps_26_27": 4,
            "goals_26_27": 1,
            "assists_26_27": 0,
            "fotmob_rating": 6.98,
            "sofascore_rating": 7.02,
            "attributes": {"Pace": 78, "Shooting": 76, "Passing": 71, "Heading": 85, "Physical": 77, "Work Rate": 83},
            "p90_metrics": {"aerial_duels_won_p90": 3.1, "shots_p90": 2.0, "pass_acc_pct": 77.0, "duel_win_pct": 56.5},
            "scouting_summary": "Famed SEA Games hero. Renowned for uncanny aerial timing, beating taller defenders to headed goals at the back post."
        },

        # --- KELANTAN DARUL NAIM FC ---
        {
            "id": 1055,
            "name": "Muhaimin Mohamad",
            "full_name": "Muhaimin bin Mohamad",
            "age": 30,
            "dob": "1995-03-22",
            "height": 182,
            "position": "Goalkeeper",
            "position_category": "Goalkeeper",
            "preferred_foot": "Right",
            "club": "Kelantan Darul Naim FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1620,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "clean_sheets_26_27": 1,
            "saves_p90": 4.1,
            "fotmob_rating": 7.10,
            "sofascore_rating": 7.14,
            "attributes": {"Shot Stopping": 80, "Reflexes": 81, "Handling": 76, "Positioning": 78, "Kicking": 73, "Physical": 77},
            "p90_metrics": {"save_pct": 78.5, "pass_acc_pct": 73.0, "duel_win_pct": 61.0},
            "scouting_summary": "Busiest goalkeeper in the league by saves per 90, constantly performing acrobatic stops under intense pressure."
        },
        {
            "id": 1056,
            "name": "Hafizal Mohamad",
            "full_name": "Mohd Hafizal bin Mohamad",
            "age": 32,
            "dob": "1993-01-12",
            "height": 179,
            "position": "Centre-Back",
            "position_category": "Defender",
            "preferred_foot": "Right",
            "club": "Kelantan Darul Naim FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1550,
            "minutes_26_27": 450,
            "apps_26_27": 5,
            "goals_26_27": 0,
            "assists_26_27": 0,
            "fotmob_rating": 7.00,
            "sofascore_rating": 7.03,
            "attributes": {"Pace": 72, "Defending": 77, "Physical": 79, "Passing": 71, "Heading": 79, "Work Rate": 82},
            "p90_metrics": {"tackles_p90": 2.5, "interceptions_p90": 2.0, "pass_acc_pct": 80.0, "duel_win_pct": 60.5},
            "scouting_summary": "Captain and defensive anchor of Kelantan Darul Naim. Physical ground battler with vocal organization."
        },
        {
            "id": 1057,
            "name": "Jasmir Mehat",
            "full_name": "Jasmir bin Mehat",
            "age": 29,
            "dob": "1996-02-06",
            "height": 173,
            "position": "Right Winger",
            "secondary_positions": ["Left Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "Kelantan Darul Naim FC",
            "league": "Malaysia Super League",
            "country": "Malaysia",
            "pool_status": "MSL Domestic Senior",
            "tier": "National Pool",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 100000,
            "minutes_25_26": 1320,
            "minutes_26_27": 380,
            "apps_26_27": 5,
            "goals_26_27": 1,
            "assists_26_27": 1,
            "fotmob_rating": 6.95,
            "sofascore_rating": 6.98,
            "attributes": {"Pace": 82, "Shooting": 72, "Passing": 71, "Dribbling": 77, "Physical": 69, "Work Rate": 79},
            "p90_metrics": {"dribbles_p90": 2.6, "crosses_p90": 2.3, "pass_acc_pct": 77.0, "duel_win_pct": 48.5},
            "scouting_summary": "Fast transition winger who spearheads Kelantan Darul Naim's breakaways."
        },

        # --- ADDITIONAL OVERSEAS TALENT ---
        {
            "id": 1060,
            "name": "Allee Putra",
            "full_name": "Muhammad Allee Putra bin Azril",
            "age": 20,
            "dob": "2005-09-12",
            "height": 176,
            "position": "Right Winger",
            "secondary_positions": ["Left Winger"],
            "position_category": "Attacker",
            "preferred_foot": "Right",
            "club": "FC Malaga City",
            "league": "Tercera RFEF (Spain)",
            "country": "Malaysia",
            "pool_status": "Heritage & Scouting Prospect",
            "tier": "Youth Development Abroad",
            "caps": 0,
            "goals": 0,
            "market_value_eur": 75000,
            "minutes_25_26": 920,
            "minutes_26_27": 270,
            "apps_26_27": 4,
            "goals_26_27": 1,
            "assists_26_27": 1,
            "fotmob_rating": 6.95,
            "sofascore_rating": 7.00,
            "attributes": {"Pace": 85, "Shooting": 73, "Passing": 72, "Dribbling": 81, "Physical": 68, "Work Rate": 78},
            "p90_metrics": {"dribbles_p90": 3.5, "key_passes_p90": 1.4, "pass_acc_pct": 78.0, "duel_win_pct": 50.0},
            "scouting_summary": "Young Malaysian talent developing in Spanish competitive football. Rapid acceleration and tight ball control in 1v1 duels."
        }
    ]

    for p in domestic_pool:
        name = p["name"]
        if name in seen_names:
            continue
        seen_names.add(name)
        if not p.get("photo_url") or "default" in p.get("photo_url", ""):
            p["photo_url"] = make_avatar(name)
        master_players.append(p)

    # 3. Calculate consistent Readiness Index and ensure all players have uniform schema
    for p in master_players:
        # Standardize numerical performance attributes
        p["minutes_26_27"] = int(p.get("minutes_26_27") or 0)
        p["minutes_25_26"] = int(p.get("minutes_25_26") or 0)
        p["apps_26_27"] = int(p.get("apps_26_27") or 0)
        p["goals_26_27"] = int(p.get("goals_26_27") or 0)
        p["assists_26_27"] = int(p.get("assists_26_27") or 0)
        p["goal_contributions_26_27"] = int(p.get("goal_contributions_26_27") or (p["goals_26_27"] + p["assists_26_27"]))
        p["market_value_eur"] = int(p.get("market_value_eur") or 100000)
        p["age"] = int(p.get("age") or 25)
        p["preferred_foot"] = p.get("preferred_foot", "Right")
        p["height"] = int(p.get("height") or 178)

        # League Tier Coefficient
        league = p.get("league", "")
        if any(top in league for top in ["Eredivisie", "MLS", "J1 League", "Bundesliga", "Premier League", "La Liga"]):
            c_league = 1.18
        elif any(t2 in league for t2 in ["J3", "Thai League", "3. Liga", "Challenger Pro", "MLS NEXT"]):
            c_league = 1.08
        else:
            c_league = 1.00 # MSL baseline

        # Age curve
        age = p.get("age", 25)
        if 23 <= age <= 28:
            f_age = 1.02 # Peak
        elif age < 23:
            f_age = 0.98 # High ceiling, lower immediate sample
        else:
            f_age = 0.97 # Veteran

        # Sample reliability
        mins = p.get("minutes_26_27", 0)
        mins_factor = min(1.03, 0.94 + (mins / 3000))

        # Attributes base
        attrs = p.get("attributes", {})
        if attrs:
            avg_attr = sum(attrs.values()) / len(attrs)
        else:
            avg_attr = 75.0

        if "readiness_index" not in p:
            readiness = round(min(96, max(60, avg_attr * c_league * f_age * mins_factor)))
            p["readiness_index"] = int(readiness)

        # Standardize avatar
        if not p.get("photo_url") or "default" in p.get("photo_url", "") or not isinstance(p.get("photo_url"), str):
            p["photo_url"] = make_avatar(p["name"])

    # Save to data/malaysia_master_player_database.json
    out_path = "data/malaysia_master_player_database.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(master_players, f, indent=2)

    print(f"Master database created successfully with {len(master_players)} Malaysian players!")

if __name__ == "__main__":
    main()
